#!/ usr/bin/perl
use v5.10;
use experimental qw(smartmatch);

# Build
$lualatex     = "lualatex -synctex=1 -interaction=nonstopmode";
$pdflualatex  = $lualatex;
$pdf_mode     = 4;
$max_repeat   = 5;
$out_dir      = "build";

# Bibliography
$biber        = "biber %O --bblencoding=utf8 -u -U --output_safechars %B";
$bibtex       = "bibtex %O %B";

# Index
$makeindex    = "mendex %O -o %D %S";

# Preview
given ($^O) {
    when ("linux") {
        $pdf_previewer = "evince";
    }
    when ("darwin") {
        $pdf_previewer = "open -a Preview %S";
    }
    default {
        $pdf_previewer = "evince";
    }
}

$success_cmd = "gs -o %Z/%B-grayscale.pdf -sDEVICE=pdfwrite -sColorConversionStrategy=Gray %D"